scope({c0_Algorithm:5, c0_Cipher:3, c0_Enum:19, c0_Mode:7, c0_Padding:2, c0_Performance:4, c0_Security:4, c0_SymmetricBlockCipher:2, c0_SymmetricCipher:2, c0_algorithmSecurity:5, c0_classPerformance:5, c0_description:5, c0_keySize:2, c0_mode:2, c0_name:5, c0_padding:2, c0_performance:5, c0_provider:5});
defaultScope(1);
intRange(-8, 7);
stringLength(43);

c0_Enum = Abstract("c0_Enum");
c0_Security = Abstract("c0_Security");
c0_Broken = Clafer("c0_Broken").withCard(1, 1);
c0_Weak = Clafer("c0_Weak").withCard(1, 1);
c0_Medium = Clafer("c0_Medium").withCard(1, 1);
c0_Strong = Clafer("c0_Strong").withCard(1, 1);
c0_Performance = Abstract("c0_Performance");
c0_VerySlow = Clafer("c0_VerySlow").withCard(1, 1);
c0_Slow = Clafer("c0_Slow").withCard(1, 1);
c0_Fast = Clafer("c0_Fast").withCard(1, 1);
c0_VeryFast = Clafer("c0_VeryFast").withCard(1, 1);
c0_Padding = Abstract("c0_Padding");
c0_NoPadding = Clafer("c0_NoPadding").withCard(1, 1);
c0_PKCS5Padding = Clafer("c0_PKCS5Padding").withCard(1, 1);
c0_AsymmetricPadding = Abstract("c0_AsymmetricPadding");
c0_OAEPWithSHA256 = Clafer("c0_OAEPWithSHA256").withCard(1, 1);
c0_Mode = Abstract("c0_Mode");
c0_ECB = Clafer("c0_ECB").withCard(1, 1);
c0_CBC = Clafer("c0_CBC").withCard(1, 1);
c0_PCBC = Clafer("c0_PCBC").withCard(1, 1);
c0_CTR = Clafer("c0_CTR").withCard(1, 1);
c0_CTS = Clafer("c0_CTS").withCard(1, 1);
c0_CFB = Clafer("c0_CFB").withCard(1, 1);
c0_OFB = Clafer("c0_OFB").withCard(1, 1);
c0_Provider = Abstract("c0_Provider");
c0_JCA = Clafer("c0_JCA").withCard(1, 1);
c0_Algorithm = Abstract("c0_Algorithm");
c0_name = c0_Algorithm.addChild("c0_name").withCard(1, 1);
c0_description = c0_Algorithm.addChild("c0_description").withCard(1, 1);
c0_algorithmSecurity = c0_Algorithm.addChild("c0_algorithmSecurity").withCard(1, 1);
c0_performance = c0_Algorithm.addChild("c0_performance").withCard(1, 1);
c0_classPerformance = c0_Algorithm.addChild("c0_classPerformance").withCard(1, 1);
c0_provider = c0_Algorithm.addChild("c0_provider").withCard(1, 1);
c0_Cipher = Abstract("c0_Cipher");
c0_SymmetricCipher = Abstract("c0_SymmetricCipher");
c0_keySize = c0_SymmetricCipher.addChild("c0_keySize").withCard(1, 1);
c0_SymmetricBlockCipher = Abstract("c0_SymmetricBlockCipher");
c0_mode = c0_SymmetricBlockCipher.addChild("c0_mode").withCard(1, 1);
c0_padding = c0_SymmetricBlockCipher.addChild("c0_padding").withCard(1, 1);
c0_Task = Abstract("c0_Task");
c1_description = c0_Task.addChild("c1_description").withCard(1, 1);
c0_SymmetricCiphers = Clafer("c0_SymmetricCiphers").withCard(1, 1).withGroupCard(1, 1);
c0_AES = c0_SymmetricCiphers.addChild("c0_AES").withCard(0, 1);
c0_DES = c0_SymmetricCiphers.addChild("c0_DES").withCard(0, 1);
c0_KeyDerivationAlgorithm = Abstract("c0_KeyDerivationAlgorithm");
c0_iterations = c0_KeyDerivationAlgorithm.addChild("c0_iterations").withCard(1, 1);
c0_outputSize = c0_KeyDerivationAlgorithm.addChild("c0_outputSize").withCard(1, 1);
c0_digest = c0_KeyDerivationAlgorithm.addChild("c0_digest").withCard(0, 1);
c0_Digest = Abstract("c0_Digest");
c1_outputSize = c0_Digest.addChild("c1_outputSize").withCard(1, 1);
c0_SHA = Clafer("c0_SHA").withCard(1, 1);
c0_pbkdf2 = Clafer("c0_pbkdf2").withCard(1, 1);
c0_AsymmetricCipher = Abstract("c0_AsymmetricCipher");
c1_mode = c0_AsymmetricCipher.addChild("c1_mode").withCard(1, 1);
c0_keySizePub = c0_AsymmetricCipher.addChild("c0_keySizePub").withCard(1, 1);
c0_keySizeSec = c0_AsymmetricCipher.addChild("c0_keySizeSec").withCard(1, 1);
c1_performance = c0_AsymmetricCipher.addChild("c1_performance").withCard(1, 1);
c1_padding = c0_AsymmetricCipher.addChild("c1_padding").withCard(1, 1);
c0_RSA = Clafer("c0_RSA").withCard(1, 1);
c0_Encryption = Clafer("c0_Encryption").withCard(1, 1);
c0_symmetricCipher = c0_Encryption.addChild("c0_symmetricCipher").withCard(1, 1);
c0_asymmetricCipher = c0_Encryption.addChild("c0_asymmetricCipher").withCard(1, 1);
c0_security = c0_Encryption.addChild("c0_security").withCard(1, 1);
c0_Security.extending(c0_Enum).refToUnique(Int);
c0_Broken.extending(c0_Security);
Constraint(implies(some(global(c0_Broken)), equal(joinRef(global(c0_Broken)), constant(1))));
c0_Weak.extending(c0_Security);
Constraint(implies(some(global(c0_Weak)), equal(joinRef(global(c0_Weak)), constant(2))));
c0_Medium.extending(c0_Security);
Constraint(implies(some(global(c0_Medium)), equal(joinRef(global(c0_Medium)), constant(3))));
c0_Strong.extending(c0_Security);
Constraint(implies(some(global(c0_Strong)), equal(joinRef(global(c0_Strong)), constant(4))));
c0_Performance.extending(c0_Enum).refToUnique(Int);
c0_VerySlow.extending(c0_Performance);
Constraint(implies(some(global(c0_VerySlow)), equal(joinRef(global(c0_VerySlow)), constant(1))));
c0_Slow.extending(c0_Performance);
Constraint(implies(some(global(c0_Slow)), equal(joinRef(global(c0_Slow)), constant(2))));
c0_Fast.extending(c0_Performance);
Constraint(implies(some(global(c0_Fast)), equal(joinRef(global(c0_Fast)), constant(3))));
c0_VeryFast.extending(c0_Performance);
Constraint(implies(some(global(c0_VeryFast)), equal(joinRef(global(c0_VeryFast)), constant(4))));
c0_Padding.extending(c0_Enum);
c0_NoPadding.extending(c0_Padding);
c0_PKCS5Padding.extending(c0_Padding);
c0_AsymmetricPadding.extending(c0_Enum).refToUnique(string);
c0_OAEPWithSHA256.extending(c0_AsymmetricPadding);
Constraint(implies(some(global(c0_OAEPWithSHA256)), equal(joinRef(global(c0_OAEPWithSHA256)), constant("\"OAEPWithSHA-256AndMGF1Padding\""))));
c0_Mode.extending(c0_Enum);
c0_ECB.extending(c0_Mode);
c0_CBC.extending(c0_Mode);
c0_PCBC.extending(c0_Mode);
c0_CTR.extending(c0_Mode);
c0_CTS.extending(c0_Mode);
c0_CFB.extending(c0_Mode);
c0_OFB.extending(c0_Mode);
c0_Provider.extending(c0_Enum);
c0_JCA.extending(c0_Provider);
c0_name.refToUnique(string);
c0_description.refToUnique(string);
c0_algorithmSecurity.refToUnique(c0_Security);
c0_performance.refToUnique(c0_Performance);
c0_classPerformance.refToUnique(c0_Performance);
c0_provider.refToUnique(c0_Provider);
c0_Cipher.extending(c0_Algorithm);
c0_SymmetricCipher.extending(c0_Cipher);
c0_keySize.refToUnique(Int);
c0_SymmetricCipher.addConstraint(equal(joinRef(join($this(), c0_classPerformance)), global(c0_Fast)));
c0_SymmetricBlockCipher.extending(c0_SymmetricCipher);
c0_mode.refToUnique(c0_Mode);
c0_padding.refToUnique(c0_Padding);
c0_SymmetricBlockCipher.addConstraint(notEqual(joinRef(join($this(), c0_mode)), global(c0_ECB)));
c0_SymmetricBlockCipher.addConstraint(notEqual(joinRef(join($this(), c0_padding)), global(c0_NoPadding)));
c1_description.refToUnique(string);
c0_AES.extending(c0_SymmetricBlockCipher);
c0_AES.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"Advanced Encryption Standard (AES) cipher\"")));
c0_AES.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"AES\"")));
c0_AES.addConstraint(or(or(equal(joinRef(join($this(), c0_keySize)), constant(128)), equal(joinRef(join($this(), c0_keySize)), constant(192))), equal(joinRef(join($this(), c0_keySize)), constant(256))));
c0_AES.addConstraint(implies(equal(joinRef(join($this(), c0_keySize)), constant(128)), and(equal(joinRef(join($this(), c0_performance)), global(c0_VeryFast)), equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Medium)))));
c0_AES.addConstraint(implies(greaterThan(joinRef(join($this(), c0_keySize)), constant(128)), and(equal(joinRef(join($this(), c0_performance)), global(c0_Fast)), equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Strong)))));
c0_DES.extending(c0_SymmetricBlockCipher);
c0_DES.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"DES encryption\"")));
c0_DES.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"DES\"")));
c0_DES.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_VeryFast)));
c0_DES.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Broken)));
c0_DES.addConstraint(equal(joinRef(join($this(), c0_keySize)), constant(56)));
c0_KeyDerivationAlgorithm.extending(c0_Algorithm);
c0_iterations.refToUnique(Int);
c0_outputSize.refToUnique(Int);
c0_digest.refToUnique(c0_Digest);
c0_KeyDerivationAlgorithm.addConstraint(equal(joinRef(join($this(), c0_outputSize)), joinRef(join(joinRef(join($this(), c0_digest)), c1_outputSize))));
c0_KeyDerivationAlgorithm.addConstraint(greaterThanEqual(joinRef(joinRef(join(joinRef(join($this(), c0_digest)), c0_algorithmSecurity))), joinRef(global(c0_Broken))));
c0_KeyDerivationAlgorithm.addConstraint(equal(joinRef(join($this(), c0_iterations)), constant(65536)));
c0_Digest.extending(c0_Algorithm);
c1_outputSize.refToUnique(Int);
c0_SHA.extending(c0_Digest);
c0_SHA.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"SHA\"")));
c0_SHA.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"SHAdigest\"")));
c0_SHA.addConstraint(or(or(or(or(equal(joinRef(join($this(), c1_outputSize)), constant(160)), equal(joinRef(join($this(), c1_outputSize)), constant(224))), equal(joinRef(join($this(), c1_outputSize)), constant(256))), equal(joinRef(join($this(), c1_outputSize)), constant(384))), equal(joinRef(join($this(), c1_outputSize)), constant(512))));
c0_SHA.addConstraint(implies(equal(joinRef(join($this(), c1_outputSize)), constant(160)), and(equal(joinRef(join($this(), c0_performance)), global(c0_VeryFast)), equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Weak)))));
c0_SHA.addConstraint(implies(equal(joinRef(join($this(), c1_outputSize)), constant(224)), and(equal(joinRef(join($this(), c0_performance)), global(c0_Fast)), equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Strong)))));
c0_SHA.addConstraint(implies(equal(joinRef(join($this(), c1_outputSize)), constant(256)), and(equal(joinRef(join($this(), c0_performance)), global(c0_Fast)), equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Strong)))));
c0_SHA.addConstraint(implies(equal(joinRef(join($this(), c1_outputSize)), constant(384)), and(equal(joinRef(join($this(), c0_performance)), global(c0_Fast)), equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Strong)))));
c0_SHA.addConstraint(implies(equal(joinRef(join($this(), c1_outputSize)), constant(512)), and(equal(joinRef(join($this(), c0_performance)), global(c0_Slow)), equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Strong)))));
c0_pbkdf2.extending(c0_KeyDerivationAlgorithm);
c0_pbkdf2.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"PBKDF2\"")));
c0_pbkdf2.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"PBKDF2 key derivation\"")));
c0_pbkdf2.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_Slow)));
c0_pbkdf2.addConstraint(some(join($this(), c0_digest)));
c0_pbkdf2.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), joinRef(join(joinRef(join($this(), c0_digest)), c0_algorithmSecurity))));
c0_AsymmetricCipher.extending(c0_Cipher);
c1_mode.refToUnique(c0_Mode);
c0_keySizePub.refToUnique(Int);
c0_keySizeSec.refToUnique(Int);
c1_performance.refToUnique(c0_Performance);
c1_padding.refToUnique(c0_AsymmetricPadding);
c0_RSA.extending(c0_AsymmetricCipher);
c0_RSA.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"RSA\"")));
c0_RSA.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"RSA Algorithm\"")));
c0_RSA.addConstraint(equal(joinRef(join($this(), c1_mode)), global(c0_ECB)));
c0_RSA.addConstraint(or(equal(joinRef(join($this(), c0_keySizePub)), constant(2048)), equal(joinRef(join($this(), c0_keySizePub)), constant(4096))));
c0_RSA.addConstraint(implies(greaterThan(joinRef(join($this(), c0_keySizePub)), constant(2048)), and(and(equal(joinRef(join($this(), c1_performance)), global(c0_Slow)), equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Strong))), equal(joinRef(join($this(), c1_padding)), global(c0_OAEPWithSHA256)))));
c0_RSA.addConstraint(equal(joinRef(join($this(), c0_keySizeSec)), joinRef(join($this(), c0_keySizePub))));
c0_Encryption.extending(c0_Task);
c0_Encryption.addConstraint(equal(joinRef(join($this(), c1_description)), constant("\"HybridEncryption\"")));
c0_symmetricCipher.refToUnique(c0_SymmetricBlockCipher);
c0_asymmetricCipher.refToUnique(c0_AsymmetricCipher);
c0_security.refToUnique(Int);
