scope({c0_Algorithm:20, c0_Cipher:8, c0_CipherSuite:54, c0_Digest:4, c0_DigitalSignatureAlgm:3, c0_Enum:20, c0_KeyAgreementAlgorithm:5, c0_Mode:4, c0_Padding:2, c0_Performance:4, c0_Security:5, c0_StreamCipher:2, c0_SymmetricBlockCipher:5, c0_SymmetricCipher:7, c0_TLS_Version:5, c0_algorithmSecurity:20, c0_cipher:54, c0_cipherSecurity:54, c0_ciphersuites:54, c0_classPerformance:20, c0_description:20, c0_keyAgreement:54, c0_keySize:7, c0_messageAuth:54, c0_mode:7, c0_name:20, c0_outputSize:4, c0_padding:5, c0_performance:20, c0_signature:54, c0_suiteSecurity:54, c0_tlsProtocol:54, c1_performance:54});
defaultScope(1);
intRange(-8, 7);
stringLength(63);

c0_Enum = Abstract("c0_Enum");
c0_Security = Abstract("c0_Security");
c0_NoSecurity = Clafer("c0_NoSecurity").withCard(1, 1);
c0_Broken = Clafer("c0_Broken").withCard(1, 1);
c0_Weak = Clafer("c0_Weak").withCard(1, 1);
c0_Medium = Clafer("c0_Medium").withCard(1, 1);
c0_Strong = Clafer("c0_Strong").withCard(1, 1);
c0_Performance = Abstract("c0_Performance");
c0_VerySlow = Clafer("c0_VerySlow").withCard(1, 1);
c0_Slow = Clafer("c0_Slow").withCard(1, 1);
c0_Fast = Clafer("c0_Fast").withCard(1, 1);
c0_VeryFast = Clafer("c0_VeryFast").withCard(1, 1);
c0_TLS_Version = Abstract("c0_TLS_Version");
c0_SSL2 = Clafer("c0_SSL2").withCard(1, 1);
c0_SSL3 = Clafer("c0_SSL3").withCard(1, 1);
c0_TLS1_0 = Clafer("c0_TLS1_0").withCard(1, 1);
c0_TLS1_1 = Clafer("c0_TLS1_1").withCard(1, 1);
c0_TLS1_2 = Clafer("c0_TLS1_2").withCard(1, 1);
c0_Padding = Abstract("c0_Padding");
c0_NoPadding = Clafer("c0_NoPadding").withCard(1, 1);
c0_PKCS5Padding = Clafer("c0_PKCS5Padding").withCard(1, 1);
c0_Mode = Abstract("c0_Mode");
c0_ECB = Clafer("c0_ECB").withCard(1, 1);
c0_CBC = Clafer("c0_CBC").withCard(1, 1);
c0_OFB = Clafer("c0_OFB").withCard(1, 1);
c0_GCM = Clafer("c0_GCM").withCard(1, 1);
c0_Algorithm = Abstract("c0_Algorithm");
c0_name = c0_Algorithm.addChild("c0_name").withCard(1, 1);
c0_description = c0_Algorithm.addChild("c0_description").withCard(1, 1);
c0_algorithmSecurity = c0_Algorithm.addChild("c0_algorithmSecurity").withCard(1, 1);
c0_performance = c0_Algorithm.addChild("c0_performance").withCard(1, 1);
c0_classPerformance = c0_Algorithm.addChild("c0_classPerformance").withCard(1, 1);
c0_Cipher = Abstract("c0_Cipher");
c0_SymmetricCipher = Abstract("c0_SymmetricCipher");
c0_keySize = c0_SymmetricCipher.addChild("c0_keySize").withCard(1, 1);
c0_mode = c0_SymmetricCipher.addChild("c0_mode").withCard(0, 1);
c0_AsymmetricCipher = Abstract("c0_AsymmetricCipher");
c0_SymmetricBlockCipher = Abstract("c0_SymmetricBlockCipher");
c0_padding = c0_SymmetricBlockCipher.addChild("c0_padding").withCard(1, 1);
c0_StreamCipher = Abstract("c0_StreamCipher");
c0_DigitalSignatureAlgm = Abstract("c0_DigitalSignatureAlgm");
c0_KeyAgreementAlgorithm = Abstract("c0_KeyAgreementAlgorithm");
c0_Digest = Abstract("c0_Digest");
c0_outputSize = c0_Digest.addChild("c0_outputSize").withCard(1, 1);
c0_Task = Abstract("c0_Task");
c1_description = c0_Task.addChild("c1_description").withCard(1, 1);
c0_AES128GCM = Clafer("c0_AES128GCM").withCard(1, 1);
c0_AES128CBC = Clafer("c0_AES128CBC").withCard(1, 1);
c0_AES256GCM = Clafer("c0_AES256GCM").withCard(1, 1);
c0_AES256CBC = Clafer("c0_AES256CBC").withCard(1, 1);
c0_TDES = Clafer("c0_TDES").withCard(1, 1);
c0_RC4128 = Clafer("c0_RC4128").withCard(1, 1);
c0_RC440 = Clafer("c0_RC440").withCard(1, 1);
c0_SHA256 = Clafer("c0_SHA256").withCard(1, 1);
c0_SHA384 = Clafer("c0_SHA384").withCard(1, 1);
c0_SHA1 = Clafer("c0_SHA1").withCard(1, 1);
c0_MD5 = Clafer("c0_MD5").withCard(1, 1);
c0_ECDHE = Clafer("c0_ECDHE").withCard(1, 1);
c0_ECDH = Clafer("c0_ECDH").withCard(1, 1);
c0_DHE = Clafer("c0_DHE").withCard(1, 1);
c0_DH = Clafer("c0_DH").withCard(1, 1);
c0_ECDSA = Clafer("c0_ECDSA").withCard(1, 1);
c0_DSS = Clafer("c0_DSS").withCard(1, 1);
c0_RSA_Sig = Clafer("c0_RSA_Sig").withCard(1, 1);
c0_RSA_Asymm = Clafer("c0_RSA_Asymm").withCard(1, 1);
c0_RSA_KeyAgr = Clafer("c0_RSA_KeyAgr").withCard(1, 1);
c0_CipherSuite = Abstract("c0_CipherSuite");
c0_cipher = c0_CipherSuite.addChild("c0_cipher").withCard(0, 1);
c0_tlsProtocol = c0_CipherSuite.addChild("c0_tlsProtocol").withCard(1, 1);
c0_keyAgreement = c0_CipherSuite.addChild("c0_keyAgreement").withCard(1, 1);
c0_signature = c0_CipherSuite.addChild("c0_signature").withCard(1, 1);
c0_messageAuth = c0_CipherSuite.addChild("c0_messageAuth").withCard(1, 1);
c0_cipherSecurity = c0_CipherSuite.addChild("c0_cipherSecurity").withCard(1, 1);
c0_suiteSecurity = c0_CipherSuite.addChild("c0_suiteSecurity").withCard(1, 1);
c1_performance = c0_CipherSuite.addChild("c1_performance").withCard(1, 1);
c0_TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 = Clafer("c0_TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384").withCard(1, 1);
c0_TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 = Clafer("c0_TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384").withCard(1, 1);
c0_TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384 = Clafer("c0_TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384").withCard(1, 1);
c0_TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 = Clafer("c0_TLS_DHE_RSA_WITH_AES_256_GCM_SHA384").withCard(1, 1);
c0_TLS_RSA_WITH_AES_256_GCM_SHA384 = Clafer("c0_TLS_RSA_WITH_AES_256_GCM_SHA384").withCard(1, 1);
c0_TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 = Clafer("c0_TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384").withCard(1, 1);
c0_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 = Clafer("c0_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384").withCard(1, 1);
c0_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 = Clafer("c0_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384").withCard(1, 1);
c0_TLS_RSA_WITH_AES_256_CBC_SHA256 = Clafer("c0_TLS_RSA_WITH_AES_256_CBC_SHA256").withCard(1, 1);
c0_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 = Clafer("c0_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384").withCard(1, 1);
c0_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 = Clafer("c0_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384").withCard(1, 1);
c0_TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 = Clafer("c0_TLS_DHE_RSA_WITH_AES_256_CBC_SHA256").withCard(1, 1);
c0_TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 = Clafer("c0_TLS_DHE_DSS_WITH_AES_256_CBC_SHA256").withCard(1, 1);
c0_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA = Clafer("c0_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA").withCard(1, 1);
c0_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA = Clafer("c0_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA").withCard(1, 1);
c0_TLS_RSA_WITH_AES_256_CBC_SHA = Clafer("c0_TLS_RSA_WITH_AES_256_CBC_SHA").withCard(1, 1);
c0_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA = Clafer("c0_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA").withCard(1, 1);
c0_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA = Clafer("c0_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA").withCard(1, 1);
c0_TLS_DHE_RSA_WITH_AES_256_CBC_SHA = Clafer("c0_TLS_DHE_RSA_WITH_AES_256_CBC_SHA").withCard(1, 1);
c0_TLS_DHE_DSS_WITH_AES_256_CBC_SHA = Clafer("c0_TLS_DHE_DSS_WITH_AES_256_CBC_SHA").withCard(1, 1);
c0_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 = Clafer("c0_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256").withCard(1, 1);
c0_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 = Clafer("c0_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256").withCard(1, 1);
c0_TLS_RSA_WITH_AES_128_CBC_SHA256 = Clafer("c0_TLS_RSA_WITH_AES_128_CBC_SHA256").withCard(1, 1);
c0_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 = Clafer("c0_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256").withCard(1, 1);
c0_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 = Clafer("c0_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256").withCard(1, 1);
c0_TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 = Clafer("c0_TLS_DHE_RSA_WITH_AES_128_CBC_SHA256").withCard(1, 1);
c0_TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 = Clafer("c0_TLS_DHE_DSS_WITH_AES_128_CBC_SHA256").withCard(1, 1);
c0_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA = Clafer("c0_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA").withCard(1, 1);
c0_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA = Clafer("c0_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA").withCard(1, 1);
c0_TLS_RSA_WITH_AES_128_CBC_SHA = Clafer("c0_TLS_RSA_WITH_AES_128_CBC_SHA").withCard(1, 1);
c0_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA = Clafer("c0_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA").withCard(1, 1);
c0_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA = Clafer("c0_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA").withCard(1, 1);
c0_TLS_DHE_RSA_WITH_AES_128_CBC_SHA = Clafer("c0_TLS_DHE_RSA_WITH_AES_128_CBC_SHA").withCard(1, 1);
c0_TLS_DHE_DSS_WITH_AES_128_CBC_SHA = Clafer("c0_TLS_DHE_DSS_WITH_AES_128_CBC_SHA").withCard(1, 1);
c0_TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 = Clafer("c0_TLS_DHE_RSA_WITH_AES_128_GCM_SHA256").withCard(1, 1);
c0_TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA = Clafer("c0_TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA").withCard(1, 1);
c0_TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA = Clafer("c0_TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA").withCard(1, 1);
c0_TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA = Clafer("c0_TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA").withCard(1, 1);
c0_TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256 = Clafer("c0_TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256").withCard(1, 1);
c0_TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256 = Clafer("c0_TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256").withCard(1, 1);
c0_TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 = Clafer("c0_TLS_DHE_DSS_WITH_AES_128_GCM_SHA256").withCard(1, 1);
c0_TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA = Clafer("c0_TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA").withCard(1, 1);
c0_TLS_RSA_WITH_AES_128_GCM_SHA256 = Clafer("c0_TLS_RSA_WITH_AES_128_GCM_SHA256").withCard(1, 1);
c0_TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 = Clafer("c0_TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256").withCard(1, 1);
c0_TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 = Clafer("c0_TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256").withCard(1, 1);
c0_TLS_ECDH_RSA_WITH_RC4_128_SHA = Clafer("c0_TLS_ECDH_RSA_WITH_RC4_128_SHA").withCard(1, 1);
c0_TLS_ECDH_ECDSA_WITH_RC4_128_SHA = Clafer("c0_TLS_ECDH_ECDSA_WITH_RC4_128_SHA").withCard(1, 1);
c0_TLS_ECDHE_ECDSA_WITH_RC4_128_SHA = Clafer("c0_TLS_ECDHE_ECDSA_WITH_RC4_128_SHA").withCard(1, 1);
c0_TLS_ECDHE_RSA_WITH_RC4_128_SHA = Clafer("c0_TLS_ECDHE_RSA_WITH_RC4_128_SHA").withCard(1, 1);
c0_SSL_RSA_WITH_3DES_EDE_CBC_SHA = Clafer("c0_SSL_RSA_WITH_3DES_EDE_CBC_SHA").withCard(1, 1);
c0_SSL_RSA_WITH_RC4_128_MD5 = Clafer("c0_SSL_RSA_WITH_RC4_128_MD5").withCard(1, 1);
c0_SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA = Clafer("c0_SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA").withCard(1, 1);
c0_SSL_RSA_WITH_RC4_128_SHA = Clafer("c0_SSL_RSA_WITH_RC4_128_SHA").withCard(1, 1);
c0_SSL_RSA_WITH_NULL_MD5 = Clafer("c0_SSL_RSA_WITH_NULL_MD5").withCard(1, 1);
c0_SecureCommunication = Clafer("c0_SecureCommunication").withCard(1, 1);
c0_ciphersuites = c0_SecureCommunication.addChild("c0_ciphersuites").withCard(7);
c0_tlsVersion = c0_SecureCommunication.addChild("c0_tlsVersion").withCard(1, 1);
c0_secComsecurity = c0_SecureCommunication.addChild("c0_secComsecurity").withCard(1, 1);
c0_Security.extending(c0_Enum).refToUnique(Int);
c0_NoSecurity.extending(c0_Security);
Constraint(implies(some(global(c0_NoSecurity)), equal(joinRef(global(c0_NoSecurity)), constant(0))));
c0_Broken.extending(c0_Security);
Constraint(implies(some(global(c0_Broken)), equal(joinRef(global(c0_Broken)), constant(1))));
c0_Weak.extending(c0_Security);
Constraint(implies(some(global(c0_Weak)), equal(joinRef(global(c0_Weak)), constant(2))));
c0_Medium.extending(c0_Security);
Constraint(implies(some(global(c0_Medium)), equal(joinRef(global(c0_Medium)), constant(3))));
c0_Strong.extending(c0_Security);
Constraint(implies(some(global(c0_Strong)), equal(joinRef(global(c0_Strong)), constant(4))));
c0_Performance.extending(c0_Enum).refToUnique(Int);
c0_VerySlow.extending(c0_Performance);
Constraint(implies(some(global(c0_VerySlow)), equal(joinRef(global(c0_VerySlow)), constant(1))));
c0_Slow.extending(c0_Performance);
Constraint(implies(some(global(c0_Slow)), equal(joinRef(global(c0_Slow)), constant(2))));
c0_Fast.extending(c0_Performance);
Constraint(implies(some(global(c0_Fast)), equal(joinRef(global(c0_Fast)), constant(3))));
c0_VeryFast.extending(c0_Performance);
Constraint(implies(some(global(c0_VeryFast)), equal(joinRef(global(c0_VeryFast)), constant(4))));
c0_TLS_Version.extending(c0_Enum).refToUnique(Int);
c0_SSL2.extending(c0_TLS_Version);
Constraint(implies(some(global(c0_SSL2)), equal(joinRef(global(c0_SSL2)), constant(1))));
c0_SSL3.extending(c0_TLS_Version);
Constraint(implies(some(global(c0_SSL3)), equal(joinRef(global(c0_SSL3)), constant(2))));
c0_TLS1_0.extending(c0_TLS_Version);
Constraint(implies(some(global(c0_TLS1_0)), equal(joinRef(global(c0_TLS1_0)), constant(3))));
c0_TLS1_1.extending(c0_TLS_Version);
Constraint(implies(some(global(c0_TLS1_1)), equal(joinRef(global(c0_TLS1_1)), constant(4))));
c0_TLS1_2.extending(c0_TLS_Version);
Constraint(implies(some(global(c0_TLS1_2)), equal(joinRef(global(c0_TLS1_2)), constant(5))));
c0_Padding.extending(c0_Enum);
c0_NoPadding.extending(c0_Padding);
c0_PKCS5Padding.extending(c0_Padding);
c0_Mode.extending(c0_Enum);
c0_ECB.extending(c0_Mode);
c0_CBC.extending(c0_Mode);
c0_OFB.extending(c0_Mode);
c0_GCM.extending(c0_Mode);
c0_name.refToUnique(string);
c0_description.refToUnique(string);
c0_algorithmSecurity.refToUnique(c0_Security);
c0_performance.refToUnique(c0_Performance);
c0_classPerformance.refToUnique(c0_Performance);
c0_Cipher.extending(c0_Algorithm);
c0_SymmetricCipher.extending(c0_Cipher);
c0_keySize.refToUnique(Int);
c0_mode.refToUnique(c0_Mode);
c0_SymmetricCipher.addConstraint(equal(joinRef(join($this(), c0_classPerformance)), global(c0_Fast)));
c0_AsymmetricCipher.extending(c0_Cipher);
c0_AsymmetricCipher.addConstraint(equal(joinRef(join($this(), c0_classPerformance)), global(c0_VerySlow)));
c0_SymmetricBlockCipher.extending(c0_SymmetricCipher);
c0_padding.refToUnique(c0_Padding);
c0_SymmetricBlockCipher.addConstraint(notEqual(joinRef(join($this(), c0_mode)), global(c0_ECB)));
c0_SymmetricBlockCipher.addConstraint(implies(equal(joinRef(join($this(), c0_mode)), global(c0_CBC)), notEqual(joinRef(join($this(), c0_padding)), global(c0_NoPadding))));
c0_StreamCipher.extending(c0_SymmetricCipher);
c0_StreamCipher.addConstraint(none(join($this(), c0_mode)));
c0_DigitalSignatureAlgm.extending(c0_Algorithm);
c0_DigitalSignatureAlgm.addConstraint(equal(joinRef(join($this(), c0_classPerformance)), global(c0_VerySlow)));
c0_KeyAgreementAlgorithm.extending(c0_Algorithm);
c0_KeyAgreementAlgorithm.addConstraint(equal(joinRef(join($this(), c0_classPerformance)), global(c0_Slow)));
c0_Digest.extending(c0_Algorithm);
c0_outputSize.refToUnique(Int);
c0_Digest.addConstraint(equal(joinRef(join($this(), c0_classPerformance)), global(c0_VeryFast)));
c1_description.refToUnique(string);
c0_AES128GCM.extending(c0_SymmetricBlockCipher);
c0_AES128GCM.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"AES\"")));
c0_AES128GCM.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"Advanced Encryption Standard (AES) cipher\"")));
c0_AES128GCM.addConstraint(equal(joinRef(join($this(), c0_keySize)), constant(128)));
c0_AES128GCM.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_VeryFast)));
c0_AES128GCM.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Medium)));
c0_AES128GCM.addConstraint(equal(joinRef(join($this(), c0_mode)), global(c0_GCM)));
c0_AES128CBC.extending(c0_SymmetricBlockCipher);
c0_AES128CBC.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"AES\"")));
c0_AES128CBC.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"Advanced Encryption Standard (AES) cipher\"")));
c0_AES128CBC.addConstraint(equal(joinRef(join($this(), c0_keySize)), constant(128)));
c0_AES128CBC.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_VeryFast)));
c0_AES128CBC.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Medium)));
c0_AES128CBC.addConstraint(equal(joinRef(join($this(), c0_mode)), global(c0_CBC)));
c0_AES256GCM.extending(c0_SymmetricBlockCipher);
c0_AES256GCM.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"AES\"")));
c0_AES256GCM.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"Advanced Encryption Standard (AES) cipher\"")));
c0_AES256GCM.addConstraint(equal(joinRef(join($this(), c0_keySize)), constant(256)));
c0_AES256GCM.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_Fast)));
c0_AES256GCM.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Strong)));
c0_AES256GCM.addConstraint(equal(joinRef(join($this(), c0_mode)), global(c0_GCM)));
c0_AES256CBC.extending(c0_SymmetricBlockCipher);
c0_AES256CBC.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"AES\"")));
c0_AES256CBC.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"Advanced Encryption Standard (AES) cipher\"")));
c0_AES256CBC.addConstraint(equal(joinRef(join($this(), c0_keySize)), constant(256)));
c0_AES256CBC.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_Fast)));
c0_AES256CBC.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Strong)));
c0_AES256CBC.addConstraint(equal(joinRef(join($this(), c0_mode)), global(c0_CBC)));
c0_TDES.extending(c0_SymmetricBlockCipher);
c0_TDES.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"3DES\"")));
c0_TDES.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"Triple Data Encryption Algorithm Encrypt-Decrypt-Encrypt mode\"")));
c0_TDES.addConstraint(equal(joinRef(join($this(), c0_keySize)), constant(168)));
c0_TDES.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_VeryFast)));
c0_TDES.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Weak)));
c0_RC4128.extending(c0_StreamCipher);
c0_RC4128.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"RC4\"")));
c0_RC4128.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"RC4 (Rivest Cipher 4)\"")));
c0_RC4128.addConstraint(equal(joinRef(join($this(), c0_keySize)), constant(128)));
c0_RC4128.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_VeryFast)));
c0_RC4128.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Broken)));
c0_RC440.extending(c0_StreamCipher);
c0_RC440.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"RC4\"")));
c0_RC440.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"RC4 (Rivest Cipher 4)\"")));
c0_RC440.addConstraint(equal(joinRef(join($this(), c0_keySize)), constant(40)));
c0_RC440.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_VeryFast)));
c0_RC440.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Broken)));
c0_SHA256.extending(c0_Digest);
c0_SHA256.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"SHA-256 digest\"")));
c0_SHA256.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"SHA-256\"")));
c0_SHA256.addConstraint(equal(joinRef(join($this(), c0_outputSize)), constant(256)));
c0_SHA256.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Strong)));
c0_SHA256.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_Fast)));
c0_SHA384.extending(c0_Digest);
c0_SHA384.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"SHA-384 digest\"")));
c0_SHA384.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"SHA-384\"")));
c0_SHA384.addConstraint(equal(joinRef(join($this(), c0_outputSize)), constant(384)));
c0_SHA384.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Strong)));
c0_SHA384.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_VerySlow)));
c0_SHA1.extending(c0_Digest);
c0_SHA1.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"SHA-1\"")));
c0_SHA1.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"SHA-1 digest\"")));
c0_SHA1.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_VeryFast)));
c0_SHA1.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Weak)));
c0_SHA1.addConstraint(equal(joinRef(join($this(), c0_outputSize)), constant(160)));
c0_MD5.extending(c0_Digest);
c0_MD5.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"MD5\"")));
c0_MD5.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"MD5 digest\"")));
c0_MD5.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_VeryFast)));
c0_MD5.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Broken)));
c0_MD5.addConstraint(equal(joinRef(join($this(), c0_outputSize)), constant(128)));
c0_ECDHE.extending(c0_KeyAgreementAlgorithm);
c0_ECDHE.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"ECDHE\"")));
c0_ECDHE.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"Key exchange algorithm\"")));
c0_ECDHE.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Strong)));
c0_ECDHE.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_VeryFast)));
c0_ECDH.extending(c0_KeyAgreementAlgorithm);
c0_ECDH.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"ECDH\"")));
c0_ECDH.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"Key exchange algorithm\"")));
c0_ECDH.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Medium)));
c0_ECDH.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_VeryFast)));
c0_DHE.extending(c0_KeyAgreementAlgorithm);
c0_DHE.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"DHE\"")));
c0_DHE.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"Key exchange algorithm\"")));
c0_DHE.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Strong)));
c0_DHE.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_Fast)));
c0_DH.extending(c0_KeyAgreementAlgorithm);
c0_DH.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"DH\"")));
c0_DH.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"Key exchange algorithm\"")));
c0_DH.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Medium)));
c0_DH.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_Fast)));
c0_ECDSA.extending(c0_DigitalSignatureAlgm);
c0_ECDSA.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"ECDSA\"")));
c0_ECDSA.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"Digital signature\"")));
c0_ECDSA.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Strong)));
c0_ECDSA.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_VeryFast)));
c0_DSS.extending(c0_DigitalSignatureAlgm);
c0_DSS.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"DSS\"")));
c0_DSS.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"Digital signature\"")));
c0_DSS.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Strong)));
c0_DSS.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_Fast)));
c0_RSA_Sig.extending(c0_DigitalSignatureAlgm);
c0_RSA_Sig.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"RSA\"")));
c0_RSA_Sig.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"RSA Algm\"")));
c0_RSA_Sig.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Strong)));
c0_RSA_Sig.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_Slow)));
c0_RSA_Asymm.extending(c0_AsymmetricCipher);
c0_RSA_Asymm.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"RSA\"")));
c0_RSA_Asymm.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"RSA Algm\"")));
c0_RSA_Asymm.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Strong)));
c0_RSA_Asymm.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_VerySlow)));
c0_RSA_KeyAgr.extending(c0_KeyAgreementAlgorithm);
c0_RSA_KeyAgr.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"RSA\"")));
c0_RSA_KeyAgr.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"RSA Algm\"")));
c0_RSA_KeyAgr.addConstraint(equal(joinRef(join($this(), c0_algorithmSecurity)), global(c0_Medium)));
c0_RSA_KeyAgr.addConstraint(equal(joinRef(join($this(), c0_performance)), global(c0_Slow)));
c0_cipher.refToUnique(c0_SymmetricCipher);
c0_tlsProtocol.refToUnique(c0_TLS_Version);
c0_keyAgreement.refToUnique(c0_KeyAgreementAlgorithm);
c0_signature.refToUnique(c0_DigitalSignatureAlgm);
c0_messageAuth.refToUnique(c0_Digest);
c0_CipherSuite.addConstraint(implies(or(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA384)), equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA256))), greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2)))));
c0_cipherSecurity.refToUnique(Int);
c0_CipherSuite.addConstraint(equal(joinRef(join($this(), c0_cipherSecurity)), ifThenElse(some(join($this(), c0_cipher)), joinRef(joinRef(join(joinRef(join($this(), c0_cipher)), c0_algorithmSecurity))), constant(0))));
c0_suiteSecurity.refToUnique(Int);
c0_CipherSuite.addConstraint(equal(joinRef(join($this(), c0_suiteSecurity)), minimum(union(union(union(joinRef(joinRef(join(joinRef(join($this(), c0_messageAuth)), c0_algorithmSecurity))), joinRef(joinRef(join(joinRef(join($this(), c0_keyAgreement)), c0_algorithmSecurity)))), joinRef(joinRef(join(joinRef(join($this(), c0_signature)), c0_algorithmSecurity)))), joinRef(join($this(), c0_cipherSecurity))))));
c1_performance.refToUnique(Int);
c0_CipherSuite.addConstraint(equal(joinRef(join($this(), c1_performance)), minimum(union(union(union(joinRef(joinRef(join(joinRef(join($this(), c0_signature)), c0_classPerformance))), joinRef(joinRef(join(joinRef(join($this(), c0_keyAgreement)), c0_classPerformance)))), joinRef(joinRef(join(joinRef(join($this(), c0_cipher)), c0_classPerformance)))), joinRef(joinRef(join(joinRef(join($this(), c0_messageAuth)), c0_classPerformance)))))));
c0_TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384.extending(c0_CipherSuite);
c0_TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256GCM)));
c0_TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_GCM)));
c0_TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDHE)));
c0_TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA384)));
c0_TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384.extending(c0_CipherSuite);
c0_TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256GCM)));
c0_TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_GCM)));
c0_TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDH)));
c0_TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_ECDSA)));
c0_TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA384)));
c0_TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384.extending(c0_CipherSuite);
c0_TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256GCM)));
c0_TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_GCM)));
c0_TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDH)));
c0_TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA384)));
c0_TLS_DHE_RSA_WITH_AES_256_GCM_SHA384.extending(c0_CipherSuite);
c0_TLS_DHE_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256GCM)));
c0_TLS_DHE_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_GCM)));
c0_TLS_DHE_RSA_WITH_AES_256_GCM_SHA384.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_DHE_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_DHE)));
c0_TLS_DHE_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_DHE_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA384)));
c0_TLS_RSA_WITH_AES_256_GCM_SHA384.extending(c0_CipherSuite);
c0_TLS_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256GCM)));
c0_TLS_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_GCM)));
c0_TLS_RSA_WITH_AES_256_GCM_SHA384.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_RSA_KeyAgr)));
c0_TLS_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_RSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA384)));
c0_TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384.extending(c0_CipherSuite);
c0_TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256GCM)));
c0_TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_GCM)));
c0_TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDHE)));
c0_TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_ECDSA)));
c0_TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA384)));
c0_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384.extending(c0_CipherSuite);
c0_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256CBC)));
c0_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDHE)));
c0_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_ECDSA)));
c0_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA384)));
c0_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384.extending(c0_CipherSuite);
c0_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256CBC)));
c0_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDHE)));
c0_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA384)));
c0_TLS_RSA_WITH_AES_256_CBC_SHA256.extending(c0_CipherSuite);
c0_TLS_RSA_WITH_AES_256_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256CBC)));
c0_TLS_RSA_WITH_AES_256_CBC_SHA256.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_RSA_WITH_AES_256_CBC_SHA256.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_RSA_WITH_AES_256_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_RSA_WITH_AES_256_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_RSA_KeyAgr)));
c0_TLS_RSA_WITH_AES_256_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA256)));
c0_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384.extending(c0_CipherSuite);
c0_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256CBC)));
c0_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDH)));
c0_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_ECDSA)));
c0_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA384)));
c0_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384.extending(c0_CipherSuite);
c0_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256CBC)));
c0_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDH)));
c0_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA384)));
c0_TLS_DHE_RSA_WITH_AES_256_CBC_SHA256.extending(c0_CipherSuite);
c0_TLS_DHE_RSA_WITH_AES_256_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256CBC)));
c0_TLS_DHE_RSA_WITH_AES_256_CBC_SHA256.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_DHE_RSA_WITH_AES_256_CBC_SHA256.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_DHE_RSA_WITH_AES_256_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_DHE)));
c0_TLS_DHE_RSA_WITH_AES_256_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_DHE_RSA_WITH_AES_256_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA256)));
c0_TLS_DHE_DSS_WITH_AES_256_CBC_SHA256.extending(c0_CipherSuite);
c0_TLS_DHE_DSS_WITH_AES_256_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256CBC)));
c0_TLS_DHE_DSS_WITH_AES_256_CBC_SHA256.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_DHE_DSS_WITH_AES_256_CBC_SHA256.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_DHE_DSS_WITH_AES_256_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_DHE)));
c0_TLS_DHE_DSS_WITH_AES_256_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_DSS)));
c0_TLS_DHE_DSS_WITH_AES_256_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA256)));
c0_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA.extending(c0_CipherSuite);
c0_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256CBC)));
c0_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDHE)));
c0_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_ECDSA)));
c0_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA.extending(c0_CipherSuite);
c0_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256CBC)));
c0_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDHE)));
c0_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_RSA_WITH_AES_256_CBC_SHA.extending(c0_CipherSuite);
c0_TLS_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256CBC)));
c0_TLS_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_RSA_KeyAgr)));
c0_TLS_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA.extending(c0_CipherSuite);
c0_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256CBC)));
c0_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDH)));
c0_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_ECDSA)));
c0_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA.extending(c0_CipherSuite);
c0_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256CBC)));
c0_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDH)));
c0_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_DHE_RSA_WITH_AES_256_CBC_SHA.extending(c0_CipherSuite);
c0_TLS_DHE_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256CBC)));
c0_TLS_DHE_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_DHE_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_DHE)));
c0_TLS_DHE_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_DHE_RSA_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_DHE_DSS_WITH_AES_256_CBC_SHA.extending(c0_CipherSuite);
c0_TLS_DHE_DSS_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES256CBC)));
c0_TLS_DHE_DSS_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_DHE_DSS_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_DHE)));
c0_TLS_DHE_DSS_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_DSS)));
c0_TLS_DHE_DSS_WITH_AES_256_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256.extending(c0_CipherSuite);
c0_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128CBC)));
c0_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDHE)));
c0_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_ECDSA)));
c0_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA256)));
c0_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256.extending(c0_CipherSuite);
c0_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128CBC)));
c0_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDHE)));
c0_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA256)));
c0_TLS_RSA_WITH_AES_128_CBC_SHA256.extending(c0_CipherSuite);
c0_TLS_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128CBC)));
c0_TLS_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_RSA_WITH_AES_128_CBC_SHA256.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_RSA_KeyAgr)));
c0_TLS_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA256)));
c0_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256.extending(c0_CipherSuite);
c0_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128CBC)));
c0_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDH)));
c0_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_ECDSA)));
c0_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA256)));
c0_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256.extending(c0_CipherSuite);
c0_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128CBC)));
c0_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDH)));
c0_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA256)));
c0_TLS_DHE_RSA_WITH_AES_128_CBC_SHA256.extending(c0_CipherSuite);
c0_TLS_DHE_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128CBC)));
c0_TLS_DHE_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_DHE_RSA_WITH_AES_128_CBC_SHA256.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_DHE_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_DHE)));
c0_TLS_DHE_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_DHE_RSA_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA256)));
c0_TLS_DHE_DSS_WITH_AES_128_CBC_SHA256.extending(c0_CipherSuite);
c0_TLS_DHE_DSS_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128CBC)));
c0_TLS_DHE_DSS_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_DHE_DSS_WITH_AES_128_CBC_SHA256.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_DHE_DSS_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_DHE)));
c0_TLS_DHE_DSS_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_DSS)));
c0_TLS_DHE_DSS_WITH_AES_128_CBC_SHA256.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA256)));
c0_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA.extending(c0_CipherSuite);
c0_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128CBC)));
c0_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDHE)));
c0_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_ECDSA)));
c0_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA.extending(c0_CipherSuite);
c0_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128CBC)));
c0_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDHE)));
c0_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_RSA_WITH_AES_128_CBC_SHA.extending(c0_CipherSuite);
c0_TLS_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128CBC)));
c0_TLS_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_RSA_KeyAgr)));
c0_TLS_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA.extending(c0_CipherSuite);
c0_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128CBC)));
c0_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDH)));
c0_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_ECDSA)));
c0_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA.extending(c0_CipherSuite);
c0_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128CBC)));
c0_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDH)));
c0_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_DHE_RSA_WITH_AES_128_CBC_SHA.extending(c0_CipherSuite);
c0_TLS_DHE_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128CBC)));
c0_TLS_DHE_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_DHE_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_DHE)));
c0_TLS_DHE_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_DHE_RSA_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_DHE_DSS_WITH_AES_128_CBC_SHA.extending(c0_CipherSuite);
c0_TLS_DHE_DSS_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128CBC)));
c0_TLS_DHE_DSS_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_DHE_DSS_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_DHE)));
c0_TLS_DHE_DSS_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_DSS)));
c0_TLS_DHE_DSS_WITH_AES_128_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_DHE_RSA_WITH_AES_128_GCM_SHA256.extending(c0_CipherSuite);
c0_TLS_DHE_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128GCM)));
c0_TLS_DHE_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_GCM)));
c0_TLS_DHE_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_DHE_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA256)));
c0_TLS_DHE_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_DHE)));
c0_TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA.extending(c0_CipherSuite);
c0_TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_TDES)));
c0_TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDHE)));
c0_TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA.extending(c0_CipherSuite);
c0_TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_TDES)));
c0_TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDH)));
c0_TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_ECDSA)));
c0_TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA.extending(c0_CipherSuite);
c0_TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_TDES)));
c0_TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDH)));
c0_TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256.extending(c0_CipherSuite);
c0_TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128GCM)));
c0_TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_GCM)));
c0_TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDH)));
c0_TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_ECDSA)));
c0_TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA256)));
c0_TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256.extending(c0_CipherSuite);
c0_TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128GCM)));
c0_TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_GCM)));
c0_TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDH)));
c0_TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA256)));
c0_TLS_DHE_DSS_WITH_AES_128_GCM_SHA256.extending(c0_CipherSuite);
c0_TLS_DHE_DSS_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128GCM)));
c0_TLS_DHE_DSS_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_GCM)));
c0_TLS_DHE_DSS_WITH_AES_128_GCM_SHA256.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_DHE_DSS_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_DHE)));
c0_TLS_DHE_DSS_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_DSS)));
c0_TLS_DHE_DSS_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA256)));
c0_TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA.extending(c0_CipherSuite);
c0_TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_TDES)));
c0_TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDHE)));
c0_TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_ECDSA)));
c0_TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_RSA_WITH_AES_128_GCM_SHA256.extending(c0_CipherSuite);
c0_TLS_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128GCM)));
c0_TLS_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_GCM)));
c0_TLS_RSA_WITH_AES_128_GCM_SHA256.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_RSA_KeyAgr)));
c0_TLS_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA256)));
c0_TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256.extending(c0_CipherSuite);
c0_TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128GCM)));
c0_TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_GCM)));
c0_TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDHE)));
c0_TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA256)));
c0_TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256.extending(c0_CipherSuite);
c0_TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_AES128GCM)));
c0_TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_GCM)));
c0_TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_TLS1_2))));
c0_TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDHE)));
c0_TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_ECDSA)));
c0_TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA256)));
c0_TLS_ECDH_RSA_WITH_RC4_128_SHA.extending(c0_CipherSuite);
c0_TLS_ECDH_RSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_RC4128)));
c0_TLS_ECDH_RSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDH)));
c0_TLS_ECDH_RSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_ECDH_RSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_ECDH_ECDSA_WITH_RC4_128_SHA.extending(c0_CipherSuite);
c0_TLS_ECDH_ECDSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_RC4128)));
c0_TLS_ECDH_ECDSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDH)));
c0_TLS_ECDH_ECDSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_ECDSA)));
c0_TLS_ECDH_ECDSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_ECDHE_ECDSA_WITH_RC4_128_SHA.extending(c0_CipherSuite);
c0_TLS_ECDHE_ECDSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_RC4128)));
c0_TLS_ECDHE_ECDSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDHE)));
c0_TLS_ECDHE_ECDSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_ECDSA)));
c0_TLS_ECDHE_ECDSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_TLS_ECDHE_RSA_WITH_RC4_128_SHA.extending(c0_CipherSuite);
c0_TLS_ECDHE_RSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_RC4128)));
c0_TLS_ECDHE_RSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_ECDHE)));
c0_TLS_ECDHE_RSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_TLS_ECDHE_RSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_SSL_RSA_WITH_3DES_EDE_CBC_SHA.extending(c0_CipherSuite);
c0_SSL_RSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_TDES)));
c0_SSL_RSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_SSL_RSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_RSA_KeyAgr)));
c0_SSL_RSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_SSL_RSA_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_SSL_RSA_WITH_3DES_EDE_CBC_SHA.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_SSL2))));
c0_SSL_RSA_WITH_RC4_128_MD5.extending(c0_CipherSuite);
c0_SSL_RSA_WITH_RC4_128_MD5.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_RC4128)));
c0_SSL_RSA_WITH_RC4_128_MD5.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_RSA_KeyAgr)));
c0_SSL_RSA_WITH_RC4_128_MD5.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_SSL_RSA_WITH_RC4_128_MD5.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_MD5)));
c0_SSL_RSA_WITH_RC4_128_MD5.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_SSL2))));
c0_SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA.extending(c0_CipherSuite);
c0_SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_TDES)));
c0_SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_mode)), global(c0_CBC)));
c0_SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_DHE)));
c0_SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_DSS)));
c0_SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_SSL2))));
c0_SSL_RSA_WITH_RC4_128_SHA.extending(c0_CipherSuite);
c0_SSL_RSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_cipher)), global(c0_RC4128)));
c0_SSL_RSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_RSA_KeyAgr)));
c0_SSL_RSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_SSL_RSA_WITH_RC4_128_SHA.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_SHA1)));
c0_SSL_RSA_WITH_RC4_128_SHA.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_SSL2))));
c0_SSL_RSA_WITH_NULL_MD5.extending(c0_CipherSuite);
c0_SSL_RSA_WITH_NULL_MD5.addConstraint(none(join($this(), c0_cipher)));
c0_SSL_RSA_WITH_NULL_MD5.addConstraint(equal(joinRef(join($this(), c0_signature)), global(c0_RSA_Sig)));
c0_SSL_RSA_WITH_NULL_MD5.addConstraint(equal(joinRef(join($this(), c0_messageAuth)), global(c0_MD5)));
c0_SSL_RSA_WITH_NULL_MD5.addConstraint(equal(joinRef(join($this(), c0_keyAgreement)), global(c0_RSA_KeyAgr)));
c0_SSL_RSA_WITH_NULL_MD5.addConstraint(greaterThanEqual(joinRef(joinRef(join($this(), c0_tlsProtocol))), joinRef(global(c0_SSL2))));
c0_SecureCommunication.extending(c0_Task);
c0_SecureCommunication.addConstraint(equal(joinRef(join($this(), c1_description)), constant("\"Establish a Secure Network Connection\"")));
c0_ciphersuites.refToUnique(c0_CipherSuite);
c0_tlsVersion.refToUnique(c0_TLS_Version);
c0_SecureCommunication.addConstraint(equal(joinRef(join($this(), c0_tlsVersion)), global(c0_TLS1_2)));
c0_secComsecurity.refToUnique(Int);
c0_SecureCommunication.addConstraint(equal(joinRef(join($this(), c0_secComsecurity)), minimum(joinRef(join(joinRef(join($this(), c0_ciphersuites)), c0_suiteSecurity)))));
