scope({c0_Enum:8, c0_Security:5, c0_TLS_Version:3, c0_tlsProtocol:3});
defaultScope(1);
intRange(-8, 7);
stringLength(39);

c0_Enum = Abstract("c0_Enum");
c0_Security = Abstract("c0_Security");
c0_NoSecurity = Clafer("c0_NoSecurity").withCard(1, 1);
c0_Broken = Clafer("c0_Broken").withCard(1, 1);
c0_Weak = Clafer("c0_Weak").withCard(1, 1);
c0_Medium = Clafer("c0_Medium").withCard(1, 1);
c0_Strong = Clafer("c0_Strong").withCard(1, 1);
c0_TLS_Version = Abstract("c0_TLS_Version");
c0_TLSv10 = Clafer("c0_TLSv10").withCard(1, 1);
c0_TLSv11 = Clafer("c0_TLSv11").withCard(1, 1);
c0_TLSv12 = Clafer("c0_TLSv12").withCard(1, 1);
c0_Task = Abstract("c0_Task");
c0_description = c0_Task.addChild("c0_description").withCard(1, 1);
c0_SecureCommunication = Clafer("c0_SecureCommunication").withCard(1, 1);
c0_tlsProtocol = c0_SecureCommunication.addChild("c0_tlsProtocol").withCard(1, 3);
c0_secComsecurity = c0_SecureCommunication.addChild("c0_secComsecurity").withCard(1, 1);
c0_Security.extending(c0_Enum).refToUnique(Int);
c0_NoSecurity.extending(c0_Security);
Constraint(implies(some(global(c0_NoSecurity)), equal(joinRef(global(c0_NoSecurity)), constant(0))));
c0_Broken.extending(c0_Security);
Constraint(implies(some(global(c0_Broken)), equal(joinRef(global(c0_Broken)), constant(1))));
c0_Weak.extending(c0_Security);
Constraint(implies(some(global(c0_Weak)), equal(joinRef(global(c0_Weak)), constant(2))));
c0_Medium.extending(c0_Security);
Constraint(implies(some(global(c0_Medium)), equal(joinRef(global(c0_Medium)), constant(3))));
c0_Strong.extending(c0_Security);
Constraint(implies(some(global(c0_Strong)), equal(joinRef(global(c0_Strong)), constant(4))));
c0_TLS_Version.extending(c0_Enum).refToUnique(Int);
c0_TLSv10.extending(c0_TLS_Version);
Constraint(implies(some(global(c0_TLSv10)), equal(joinRef(global(c0_TLSv10)), constant(3))));
c0_TLSv11.extending(c0_TLS_Version);
Constraint(implies(some(global(c0_TLSv11)), equal(joinRef(global(c0_TLSv11)), constant(4))));
c0_TLSv12.extending(c0_TLS_Version);
Constraint(implies(some(global(c0_TLSv12)), equal(joinRef(global(c0_TLSv12)), constant(5))));
c0_description.refToUnique(string);
c0_SecureCommunication.extending(c0_Task);
c0_SecureCommunication.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"Establish a Secure Network Connection\"")));
c0_tlsProtocol.refToUnique(c0_TLS_Version);
c0_secComsecurity.refToUnique(Int);
