/*
 * generated by Xtext 2.25.0
 */
package de.cognicrypt.order.editor.ide;


/**
 * Use this class to register ide components.
 */
public class StatemachineIdeModule extends AbstractStatemachineIdeModule {
}
