/*
 * generated by Xtext 2.25.0
 */
package de.cognicrypt.order.editor.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.cognicrypt.order.editor.StatemachineRuntimeModule;
import de.cognicrypt.order.editor.StatemachineStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class StatemachineIdeSetup extends StatemachineStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new StatemachineRuntimeModule(), new StatemachineIdeModule()));
	}
	
}
