/**
 * generated by Xtext 2.25.0
 */
package de.cognicrypt.order.editor.statemachine;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statemachine</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cognicrypt.order.editor.statemachine.Statemachine#getStates <em>States</em>}</li>
 *   <li>{@link de.cognicrypt.order.editor.statemachine.Statemachine#getTransitions <em>Transitions</em>}</li>
 * </ul>
 *
 * @see de.cognicrypt.order.editor.statemachine.StatemachinePackage#getStatemachine()
 * @model
 * @generated
 */
public interface Statemachine extends EObject
{
  /**
   * Returns the value of the '<em><b>States</b></em>' containment reference list.
   * The list contents are of type {@link de.cognicrypt.order.editor.statemachine.State}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>States</em>' containment reference list.
   * @see de.cognicrypt.order.editor.statemachine.StatemachinePackage#getStatemachine_States()
   * @model containment="true"
   * @generated
   */
  EList<State> getStates();

  /**
   * Returns the value of the '<em><b>Transitions</b></em>' containment reference list.
   * The list contents are of type {@link de.cognicrypt.order.editor.statemachine.Transition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transitions</em>' containment reference list.
   * @see de.cognicrypt.order.editor.statemachine.StatemachinePackage#getStatemachine_Transitions()
   * @model containment="true"
   * @generated
   */
  EList<Transition> getTransitions();

} // Statemachine
