/**
 * generated by Xtext 2.25.0
 */
package de.cognicrypt.order.editor.statemachine;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cognicrypt.order.editor.statemachine.Transition#getName <em>Name</em>}</li>
 *   <li>{@link de.cognicrypt.order.editor.statemachine.Transition#getFromState <em>From State</em>}</li>
 *   <li>{@link de.cognicrypt.order.editor.statemachine.Transition#getEvent <em>Event</em>}</li>
 *   <li>{@link de.cognicrypt.order.editor.statemachine.Transition#getEndState <em>End State</em>}</li>
 * </ul>
 *
 * @see de.cognicrypt.order.editor.statemachine.StatemachinePackage#getTransition()
 * @model
 * @generated
 */
public interface Transition extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.cognicrypt.order.editor.statemachine.StatemachinePackage#getTransition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.cognicrypt.order.editor.statemachine.Transition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>From State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From State</em>' reference.
   * @see #setFromState(State)
   * @see de.cognicrypt.order.editor.statemachine.StatemachinePackage#getTransition_FromState()
   * @model
   * @generated
   */
  State getFromState();

  /**
   * Sets the value of the '{@link de.cognicrypt.order.editor.statemachine.Transition#getFromState <em>From State</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From State</em>' reference.
   * @see #getFromState()
   * @generated
   */
  void setFromState(State value);

  /**
   * Returns the value of the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event</em>' reference.
   * @see #setEvent(Event)
   * @see de.cognicrypt.order.editor.statemachine.StatemachinePackage#getTransition_Event()
   * @model
   * @generated
   */
  Event getEvent();

  /**
   * Sets the value of the '{@link de.cognicrypt.order.editor.statemachine.Transition#getEvent <em>Event</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event</em>' reference.
   * @see #getEvent()
   * @generated
   */
  void setEvent(Event value);

  /**
   * Returns the value of the '<em><b>End State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End State</em>' reference.
   * @see #setEndState(State)
   * @see de.cognicrypt.order.editor.statemachine.StatemachinePackage#getTransition_EndState()
   * @model
   * @generated
   */
  State getEndState();

  /**
   * Sets the value of the '{@link de.cognicrypt.order.editor.statemachine.Transition#getEndState <em>End State</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End State</em>' reference.
   * @see #getEndState()
   * @generated
   */
  void setEndState(State value);

} // Transition
