scope({c0_Gender:3, c0_Person:3, c0_Task:3, c0_age:3, c0_name:3});
defaultScope(1);
intRange(-8, 7);
stringLength(16);

c0_Task = Abstract("c0_Task");
c0_Person = Abstract("c0_Person");
c0_name = c0_Person.addChild("c0_name").withCard(1, 1);
c0_age = c0_Person.addChild("c0_age").withCard(1, 1);
c0_Gender = c0_Person.addChild("c0_Gender").withCard(1, 1);
c0_Bob = Clafer("c0_Bob").withCard(1, 1).extending(c0_Person);
c0_Alice = Clafer("c0_Alice").withCard(1, 1).extending(c0_Person);
c0_Trudy = Clafer("c0_Trudy").withCard(1, 1).extending(c0_Person);
c0_myTask = Clafer("c0_myTask").withCard(1, 1).extending(c0_Task);
c0_person = c0_myTask.addChild("c0_person").withCard(1, 1);
c0_myTask2 = Clafer("c0_myTask2").withCard(1, 1).extending(c0_Task);
c1_person = c0_myTask2.addChild("c1_person").withCard(1, 1);
c0_myTask3 = Clafer("c0_myTask3").withCard(1, 1).extending(c0_Task);
c2_person = c0_myTask3.addChild("c2_person").withCard(1, 1);
c0_name.refTo(string);
c0_age.refTo(Int);
c0_Gender.refTo(string);
c0_person.refTo(c0_Person);
c1_person.refTo(c0_Person);
c2_person.refTo(c0_Person);
c0_Bob.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"bob\"")));
c0_Bob.addConstraint(equal(joinRef(join($this(), c0_age)), constant(20)));
c0_Bob.addConstraint(equal(joinRef(join($this(), c0_Gender)), constant("\"M\"")));
c0_Alice.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"alice\"")));
c0_Alice.addConstraint(equal(joinRef(join($this(), c0_age)), constant(25)));
c0_Alice.addConstraint(equal(joinRef(join($this(), c0_Gender)), constant("\"F\"")));
c0_Trudy.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"Trudy\"")));
c0_Trudy.addConstraint(equal(joinRef(join($this(), c0_age)), constant(30)));
c0_Trudy.addConstraint(equal(joinRef(join($this(), c0_Gender)), constant("\"M\"")));
c1_person.addConstraint(greaterThan(joinRef(join(joinRef($this()), c0_age)), constant(22)));
c2_person.addConstraint(greaterThan(joinRef(join(joinRef($this()), c0_age)), constant(22)));
c2_person.addConstraint(equal(joinRef(join(joinRef($this()), c0_Gender)), constant("\"M\"")));
