scope({c0_Fem:3, c0_Gender:3, c0_Male:3, c0_Person:3, c0_age:3, c0_name:3});
defaultScope(1);
intRange(-8, 7);
stringLength(16);

c0_Task = Abstract("c0_Task");
c0_Person = Abstract("c0_Person");
c0_name = c0_Person.addChild("c0_name").withCard(1, 1);
c0_age = c0_Person.addChild("c0_age").withCard(1, 1);
c0_Gender = c0_Person.addChild("c0_Gender").withCard(1, 1).withGroupCard(1);
c0_Male = c0_Gender.addChild("c0_Male").withCard(0, 1);
c0_Fem = c0_Gender.addChild("c0_Fem").withCard(0, 1);
c0_Bob = Clafer("c0_Bob").withCard(1, 1).extending(c0_Person);
c0_Alice = Clafer("c0_Alice").withCard(1, 1).extending(c0_Person);
c0_Trudy = Clafer("c0_Trudy").withCard(1, 1).extending(c0_Person);
c0_myTask = Clafer("c0_myTask").withCard(1, 1).extending(c0_Task);
c0_person = c0_myTask.addChild("c0_person").withCard(1, 1);
c0_name.refTo(string);
c0_age.refTo(Int);
c0_person.refTo(c0_Person);
c0_Bob.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"bob\"")));
c0_Bob.addConstraint(equal(joinRef(join($this(), c0_age)), constant(20)));
c0_Bob.addConstraint(some(join(join($this(), c0_Gender), c0_Male)));
c0_Alice.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"alice\"")));
c0_Alice.addConstraint(equal(joinRef(join($this(), c0_age)), constant(25)));
c0_Alice.addConstraint(some(join(join($this(), c0_Gender), c0_Fem)));
c0_Trudy.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"Trudy\"")));
c0_Trudy.addConstraint(equal(joinRef(join($this(), c0_age)), constant(30)));
c0_Trudy.addConstraint(some(join(join($this(), c0_Gender), c0_Male)));
c0_myTask.addConstraint(some(join(join(global(c0_Person), c0_Gender), c0_Fem)));
