scope({c0_Algorithm:8, c0_Cipher:2, c0_Digest:3, c0_Enum:12, c0_KeyDerivationAlgorithm:3, c0_Mode:2, c0_Padding:2, c0_Performance:4, c0_Security:4, c0_SymmetricBlockCipher:2, c0_SymmetricCipher:2, c0_classPerformance:8, c0_description:8, c0_digest:3, c0_iterations:3, c0_keySize:2, c0_mode:2, c0_name:8, c0_outputSize:3, c0_padding:2, c0_performance:8, c0_security:8, c1_outputSize:3});
defaultScope(1);
intRange(-8, 7);
stringLength(43);

c0_Enum = Abstract("c0_Enum");
c0_Security = Abstract("c0_Security");
c0_Broken = Clafer("c0_Broken").withCard(1, 1);
c0_Weak = Clafer("c0_Weak").withCard(1, 1);
c0_Medium = Clafer("c0_Medium").withCard(1, 1);
c0_Strong = Clafer("c0_Strong").withCard(1, 1);
c0_Performance = Abstract("c0_Performance");
c0_VerySlow = Clafer("c0_VerySlow").withCard(1, 1);
c0_Slow = Clafer("c0_Slow").withCard(1, 1);
c0_Fast = Clafer("c0_Fast").withCard(1, 1);
c0_VeryFast = Clafer("c0_VeryFast").withCard(1, 1);
c0_Padding = Abstract("c0_Padding");
c0_NoPadding = Clafer("c0_NoPadding").withCard(1, 1);
c0_PKCS5Padding = Clafer("c0_PKCS5Padding").withCard(1, 1);
c0_Mode = Abstract("c0_Mode");
c0_ECB = Clafer("c0_ECB").withCard(1, 1);
c0_CBC = Clafer("c0_CBC").withCard(1, 1);
c0_Algorithm = Abstract("c0_Algorithm");
c0_name = c0_Algorithm.addChild("c0_name").withCard(1, 1);
c0_description = c0_Algorithm.addChild("c0_description").withCard(1, 1);
c0_security = c0_Algorithm.addChild("c0_security").withCard(1, 1);
c0_performance = c0_Algorithm.addChild("c0_performance").withCard(1, 1);
c0_classPerformance = c0_Algorithm.addChild("c0_classPerformance").withCard(1, 1);
c0_Cipher = Abstract("c0_Cipher");
c0_SymmetricCipher = Abstract("c0_SymmetricCipher");
c0_keySize = c0_SymmetricCipher.addChild("c0_keySize").withCard(1, 1);
c0_SymmetricBlockCipher = Abstract("c0_SymmetricBlockCipher");
c0_mode = c0_SymmetricBlockCipher.addChild("c0_mode").withCard(1, 1);
c0_padding = c0_SymmetricBlockCipher.addChild("c0_padding").withCard(1, 1);
c0_KeyDerivationAlgorithm = Abstract("c0_KeyDerivationAlgorithm");
c0_iterations = c0_KeyDerivationAlgorithm.addChild("c0_iterations").withCard(1, 1);
c0_outputSize = c0_KeyDerivationAlgorithm.addChild("c0_outputSize").withCard(1, 1);
c0_digest = c0_KeyDerivationAlgorithm.addChild("c0_digest").withCard(0, 1);
c0_Digest = Abstract("c0_Digest");
c1_outputSize = c0_Digest.addChild("c1_outputSize").withCard(1, 1);
c0_Task = Abstract("c0_Task");
c1_description = c0_Task.addChild("c1_description").withCard(1, 1);
c0_Ciphers = Clafer("c0_Ciphers").withCard(1, 1).withGroupCard(1, 1);
c0_AES = c0_Ciphers.addChild("c0_AES").withCard(0, 1);
c0_DES = c0_Ciphers.addChild("c0_DES").withCard(0, 1);
c0_DigestAlgorithms = Clafer("c0_DigestAlgorithms").withCard(1, 1).withGroupCard(1, 1);
c0_md5 = c0_DigestAlgorithms.addChild("c0_md5").withCard(0, 1);
c0_sha_1 = c0_DigestAlgorithms.addChild("c0_sha_1").withCard(0, 1);
c0_sha_256 = c0_DigestAlgorithms.addChild("c0_sha_256").withCard(0, 1);
c0_KeyDerivationAlgorithms = Clafer("c0_KeyDerivationAlgorithms").withCard(1, 1).withGroupCard(1, 1);
c0_pbkdf2 = c0_KeyDerivationAlgorithms.addChild("c0_pbkdf2").withCard(0, 1);
c0_scrypt = c0_KeyDerivationAlgorithms.addChild("c0_scrypt").withCard(0, 1);
c0_bcrypt = c0_KeyDerivationAlgorithms.addChild("c0_bcrypt").withCard(0, 1);
c0_PasswordBasedEncryption = Clafer("c0_PasswordBasedEncryption").withCard(1, 1);
c0_kda = c0_PasswordBasedEncryption.addChild("c0_kda").withCard(1, 1);
c0_cipher = c0_PasswordBasedEncryption.addChild("c0_cipher").withCard(1, 1);
c0_Security.extending(c0_Enum).refToUnique(Int);
c0_Broken.extending(c0_Security);
Constraint(implies(some(global(c0_Broken)), equal(joinRef(global(c0_Broken)), constant(1))));
c0_Weak.extending(c0_Security);
Constraint(implies(some(global(c0_Weak)), equal(joinRef(global(c0_Weak)), constant(2))));
c0_Medium.extending(c0_Security);
Constraint(implies(some(global(c0_Medium)), equal(joinRef(global(c0_Medium)), constant(3))));
c0_Strong.extending(c0_Security);
Constraint(implies(some(global(c0_Strong)), equal(joinRef(global(c0_Strong)), constant(4))));
c0_Performance.extending(c0_Enum).refToUnique(Int);
c0_VerySlow.extending(c0_Performance);
Constraint(implies(some(global(c0_VerySlow)), equal(joinRef(global(c0_VerySlow)), constant(1))));
c0_Slow.extending(c0_Performance);
Constraint(implies(some(global(c0_Slow)), equal(joinRef(global(c0_Slow)), constant(2))));
c0_Fast.extending(c0_Performance);
Constraint(implies(some(global(c0_Fast)), equal(joinRef(global(c0_Fast)), constant(3))));
c0_VeryFast.extending(c0_Performance);
Constraint(implies(some(global(c0_VeryFast)), equal(joinRef(global(c0_VeryFast)), constant(4))));
c0_Padding.extending(c0_Enum);
c0_NoPadding.extending(c0_Padding);
c0_PKCS5Padding.extending(c0_Padding);
c0_Mode.extending(c0_Enum);
c0_ECB.extending(c0_Mode);
c0_CBC.extending(c0_Mode);
c0_name.refTo(string);
c0_description.refTo(string);
c0_security.refTo(Int);
c0_performance.refTo(Int);
c0_classPerformance.refTo(c0_Performance);
c0_Cipher.extending(c0_Algorithm);
c0_SymmetricCipher.extending(c0_Cipher);
c0_keySize.refTo(Int);
c0_SymmetricCipher.addConstraint(equal(joinRef(join($this(), c0_classPerformance)), global(c0_Fast)));
c0_SymmetricBlockCipher.extending(c0_SymmetricCipher);
c0_mode.refTo(c0_Mode);
c0_padding.refTo(c0_Padding);
c0_SymmetricBlockCipher.addConstraint(notEqual(joinRef(join($this(), c0_mode)), global(c0_ECB)));
c0_SymmetricBlockCipher.addConstraint(notEqual(joinRef(join($this(), c0_padding)), global(c0_NoPadding)));
c0_KeyDerivationAlgorithm.extending(c0_Algorithm);
c0_iterations.refTo(Int);
c0_outputSize.refTo(Int);
c0_digest.refTo(c0_Digest);
c0_KeyDerivationAlgorithm.addConstraint(or(or(equal(joinRef(join($this(), c0_outputSize)), constant(128)), equal(joinRef(join($this(), c0_outputSize)), constant(192))), equal(joinRef(join($this(), c0_outputSize)), constant(256))));
c0_KeyDerivationAlgorithm.addConstraint(notEqual(joinRef(join(joinRef(join($this(), c0_digest)), c0_security)), joinRef(global(c0_Broken))));
c0_KeyDerivationAlgorithm.addConstraint(equal(joinRef(join($this(), c0_iterations)), constant(1000)));
c0_Digest.extending(c0_Algorithm);
c1_outputSize.refTo(Int);
c1_description.refTo(string);
c0_AES.extending(c0_SymmetricBlockCipher);
c0_AES.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"Advanced Encryption Standard (AES) cipher\"")));
c0_AES.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"AES\"")));
c0_AES.addConstraint(or(or(equal(joinRef(join($this(), c0_keySize)), constant(128)), equal(joinRef(join($this(), c0_keySize)), constant(192))), equal(joinRef(join($this(), c0_keySize)), constant(256))));
c0_AES.addConstraint(implies(equal(joinRef(join($this(), c0_keySize)), constant(128)), and(equal(joinRef(join($this(), c0_performance)), joinRef(global(c0_VeryFast))), equal(joinRef(join($this(), c0_security)), joinRef(global(c0_Medium))))));
c0_AES.addConstraint(implies(greaterThan(joinRef(join($this(), c0_keySize)), constant(128)), and(equal(joinRef(join($this(), c0_performance)), joinRef(global(c0_Fast))), equal(joinRef(join($this(), c0_security)), joinRef(global(c0_Strong))))));
c0_DES.extending(c0_SymmetricBlockCipher);
c0_DES.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"DES encryption\"")));
c0_DES.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"DES\"")));
c0_DES.addConstraint(equal(joinRef(join($this(), c0_performance)), joinRef(global(c0_VeryFast))));
c0_DES.addConstraint(equal(joinRef(join($this(), c0_security)), joinRef(global(c0_Broken))));
c0_DES.addConstraint(equal(joinRef(join($this(), c0_keySize)), constant(56)));
c0_md5.extending(c0_Digest);
c0_md5.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"MD5\"")));
c0_md5.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"MD5 digest\"")));
c0_md5.addConstraint(equal(joinRef(join($this(), c0_performance)), joinRef(global(c0_VeryFast))));
c0_md5.addConstraint(equal(joinRef(join($this(), c0_security)), joinRef(global(c0_Broken))));
c0_md5.addConstraint(equal(joinRef(join($this(), c1_outputSize)), constant(128)));
c0_sha_1.extending(c0_Digest);
c0_sha_1.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"SHA-1\"")));
c0_sha_1.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"SHA-1 digest\"")));
c0_sha_1.addConstraint(equal(joinRef(join($this(), c0_performance)), joinRef(global(c0_VeryFast))));
c0_sha_1.addConstraint(equal(joinRef(join($this(), c0_security)), joinRef(global(c0_Weak))));
c0_sha_1.addConstraint(equal(joinRef(join($this(), c1_outputSize)), constant(160)));
c0_sha_256.extending(c0_Digest);
c0_sha_256.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"SHA-256\"")));
c0_sha_256.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"SHA-256 digest\"")));
c0_sha_256.addConstraint(equal(joinRef(join($this(), c1_outputSize)), constant(256)));
c0_sha_256.addConstraint(equal(joinRef(join($this(), c0_security)), joinRef(global(c0_Strong))));
c0_sha_256.addConstraint(equal(joinRef(join($this(), c0_performance)), joinRef(global(c0_Slow))));
c0_pbkdf2.extending(c0_KeyDerivationAlgorithm);
c0_pbkdf2.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"PBKDF2\"")));
c0_pbkdf2.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"PBKDF2 key derivation\"")));
c0_pbkdf2.addConstraint(equal(joinRef(join($this(), c0_performance)), joinRef(global(c0_Slow))));
c0_pbkdf2.addConstraint(some(join($this(), c0_digest)));
c0_pbkdf2.addConstraint(equal(joinRef(join($this(), c0_security)), joinRef(join(joinRef(join($this(), c0_digest)), c0_security))));
c0_scrypt.extending(c0_KeyDerivationAlgorithm);
c0_scrypt.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"scrypt\"")));
c0_scrypt.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"Scrypt password-based key derivation\"")));
c0_scrypt.addConstraint(none(join($this(), c0_digest)));
c0_scrypt.addConstraint(equal(joinRef(join($this(), c0_performance)), joinRef(global(c0_VerySlow))));
c0_scrypt.addConstraint(equal(joinRef(join($this(), c0_security)), joinRef(global(c0_Strong))));
c0_bcrypt.extending(c0_KeyDerivationAlgorithm);
c0_bcrypt.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"bcrypt\"")));
c0_bcrypt.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"Bcrypt password-based key derivation\"")));
c0_bcrypt.addConstraint(none(join($this(), c0_digest)));
c0_bcrypt.addConstraint(equal(joinRef(join($this(), c0_performance)), joinRef(global(c0_Slow))));
c0_bcrypt.addConstraint(equal(joinRef(join($this(), c0_outputSize)), constant(192)));
c0_bcrypt.addConstraint(equal(joinRef(join($this(), c0_security)), joinRef(global(c0_Medium))));
c0_PasswordBasedEncryption.extending(c0_Task);
c0_PasswordBasedEncryption.addConstraint(equal(joinRef(join($this(), c1_description)), constant("\"Encrypt data using a given password\"")));
c0_kda.refTo(c0_KeyDerivationAlgorithm);
c0_cipher.refTo(c0_SymmetricBlockCipher);
c0_PasswordBasedEncryption.addConstraint(equal(joinRef(join(joinRef(join($this(), c0_cipher)), c0_keySize)), joinRef(join(joinRef(join($this(), c0_kda)), c0_outputSize))));
