scope({c0_BMW_F:2, c0_CAR:4, c0_TESLA:2, c0_class:2, c0_name:4, c0_performance:4, c0_power:2});
defaultScope(1);
intRange(-8, 7);
stringLength(16);

c0_CAR = Abstract("c0_CAR");
c0_Task = Abstract("c0_Task");
c0_BMW_F = Abstract("c0_BMW_F").extending(c0_CAR);
c0_TESLA = Abstract("c0_TESLA").extending(c0_CAR);
c0_name = c0_CAR.addChild("c0_name").withCard(1, 1);
c0_performance = c0_CAR.addChild("c0_performance").withCard(1, 1);
c0_class = c0_BMW_F.addChild("c0_class").withCard(1, 1);
c0_power = c0_TESLA.addChild("c0_power").withCard(1, 1);
c0_description = c0_Task.addChild("c0_description").withCard(1, 1);
c0_BMWCars = Clafer("c0_BMWCars").withCard(1, 1);
c0_F30 = c0_BMWCars.addChild("c0_F30").withCard(1, 1).extending(c0_BMW_F);
c0_F87 = c0_BMWCars.addChild("c0_F87").withCard(1, 1).extending(c0_BMW_F);
c0_TeslaCars = Clafer("c0_TeslaCars").withCard(1, 1);
c0_ModelS = c0_TeslaCars.addChild("c0_ModelS").withCard(1, 1).extending(c0_TESLA);
c0_Model3 = c0_TeslaCars.addChild("c0_Model3").withCard(1, 1).extending(c0_TESLA);
c0_CarFinder = Clafer("c0_CarFinder").withCard(1, 1).extending(c0_Task);
c0_optionPetrol = c0_CarFinder.addChild("c0_optionPetrol").withCard(1, 1);
c0_optionElectric = c0_CarFinder.addChild("c0_optionElectric").withCard(1, 1);
c0_name.refTo(string);
c0_performance.refTo(Int);
c0_class.refTo(Int);
c0_power.refTo(Int);
c0_description.refTo(string);
c0_optionPetrol.refTo(c0_BMW_F);
c0_optionElectric.refTo(c0_TESLA);
c0_F30.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"BMW F30\"")));
c0_F30.addConstraint(equal(joinRef(join($this(), c0_class)), constant(4)));
c0_F30.addConstraint(equal(joinRef(join($this(), c0_performance)), constant(3)));
c0_F87.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"BMW F87\"")));
c0_F87.addConstraint(equal(joinRef(join($this(), c0_performance)), constant(1)));
c0_F87.addConstraint(equal(joinRef(join($this(), c0_class)), constant(2)));
c0_ModelS.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"Model S\"")));
c0_ModelS.addConstraint(equal(joinRef(join($this(), c0_performance)), constant(2)));
c0_ModelS.addConstraint(equal(joinRef(join($this(), c0_power)), constant(3)));
c0_Model3.addConstraint(equal(joinRef(join($this(), c0_name)), constant("\"Model 3\"")));
c0_Model3.addConstraint(equal(joinRef(join($this(), c0_performance)), constant(3)));
c0_Model3.addConstraint(equal(joinRef(join($this(), c0_power)), constant(2)));
c0_CarFinder.addConstraint(equal(joinRef(join($this(), c0_description)), constant("\"Find car\"")));