/*
 * generated by Xtext 2.25.0
 */
package de.cognicrypt.order.editor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class StatemachineUiModule extends AbstractStatemachineUiModule {

	public StatemachineUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
