/*
 * generated by Xtext 2.25.0
 */
package de.cognicrypt.order.editor.scoping;

import org.eclipse.xtext.xbase.scoping.XtypeScopeProvider;

public abstract class AbstractStatemachineScopeProvider extends XtypeScopeProvider {
}
