/*
 * generated by Xtext 2.25.0
 */
package de.cognicrypt.order.editor.ui;

import com.google.inject.Injector;
import de.cognicrypt.order.editor.ui.internal.EditorActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StatemachineExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(EditorActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		EditorActivator activator = EditorActivator.getInstance();
		return activator != null ? activator.getInjector(EditorActivator.DE_COGNICRYPT_ORDER_EDITOR_STATEMACHINE) : null;
	}

}
