/*
 * generated by Xtext 2.25.0
 */
package de.cognicrypt.order.editor.ui.tests;

import com.google.inject.Injector;
import de.cognicrypt.order.editor.ui.internal.EditorActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class StatemachineUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EditorActivator.getInstance().getInjector("de.cognicrypt.order.editor.Statemachine");
	}

}
