/*
 * generated by Xtext 2.25.0
 */
package de.cognicrypt.order.editor;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class StatemachineStandaloneSetup extends StatemachineStandaloneSetupGenerated {

	public static void doSetup() {
		new StatemachineStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
