/*
 * generated by Xtext 2.25.0
 */
package de.cognicrypt.order.editor;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StatemachineRuntimeModule extends AbstractStatemachineRuntimeModule {
}
